import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from Foe import Foe    # NOQA
from InvokePSQL import InvokePSQL    # NOQA
from CommonFunctions import arrayToString, stringToArray    # NOQA
from CommonFunctions import compareArrays    # NOQA


def test_Foe_Default():
    db = InvokePSQL()
    a1 = Foe(db)
    assert(a1)
    assert(a1.getName())
    assert(a1.getRawAbilityArray())
    assert(a1.getAbilityArray())
    assert(a1.level)
    assert(a1.getAlignmentStr())
    assert(a1.getAlignmentAbbrev())
    assert(a1.blinded_ind is False)
    assert(a1.charmed_ind is False)
    assert(a1.deafend_ind is False)
    assert(a1.fatigued_ind is False)
    assert(a1.frightened_ind is False)
    assert(a1.grappled_ind is False)
    assert(a1.incapacitated_ind is False)
    assert(a1.invisible_ind is False)
    assert(a1.paralyzed_ind is False)
    assert(a1.petrified_ind is False)
    assert(a1.poisoned_ind is False)
    assert(a1.prone_ind is False)
    assert(a1.stunned_ind is False)
    assert(a1.unconcious_ind is False)
    assert(a1.alive is True)
    assert(a1.stabilized is True)
    assert(a1.exhaustion_level == 0)
    assert(a1.cur_movement > 10)


def test_Foe_Skeleton():
    db = InvokePSQL()
    a1 = Foe(db, foeCandidate='Skeleton', debugInd=1)
    assert(a1)
    assert(a1.getName() == 'Skeleton')
    assert(a1.foe_type == "Undead")
    assert(arrayToString(a1.getRawAbilityArray()) == "10,14,15,6,8,5")
    assert(arrayToString(a1.getAbilityArray()) == "10,14,15,6,8,5")
    assert(a1.level == 1)
    assert(a1.challenge_level == .25)
    assert(a1.getAlignmentStr() == 'Lawful evil')
    assert(a1.getAlignmentAbbrev() == 'LE')
    assert(a1.hit_points == 20)
    assert(a1.ranged_weapon == "Shortbow")
    assert(a1.melee_weapon == "Shortsword")
    assert(a1.ranged_ammunition_type == "Arrow")
    assert(a1.ranged_ammunition_amt == 20)
    assert(a1.armor == "Scraps")
    assert(a1.source_material == "SRD5")
    assert(a1.cur_movement == 30)


def test_Foe_Gnoll():
    db = InvokePSQL()
    a1 = Foe(db, foeCandidate='Gnoll', debugInd=1)
    assert(a1)
    assert(a1.getName() == 'Gnoll')
    assert(a1.foe_type == "Humanoid")
    assert(arrayToString(a1.getRawAbilityArray()) == "14,12,11,6,10,7")
    assert(arrayToString(a1.getAbilityArray()) == "14,12,11,6,10,7")
    assert(a1.level == 1)
    assert(a1.challenge_level == .50)
    assert(a1.getAlignmentStr() == 'Chaotic evil')
    assert(a1.getAlignmentAbbrev() == 'CE')
    assert(a1.hit_points == 40)
    assert(a1.ranged_weapon == "Longbow")
    assert(a1.melee_weapon == "Spear")
    assert(a1.ranged_ammunition_type == "Arrow")
    assert(a1.ranged_ammunition_amt == 20)
    assert(a1.armor == "Hide")
    assert(a1.source_material == "SRD5")
    assert(a1.cur_movement == 30)


def test_Foe_Gnoll_Death():
    db = InvokePSQL()
    a1 = Foe(db, foeCandidate='Gnoll', debugInd=1)
    assert(a1)
    assert(a1.getName() == 'Gnoll')
    a1.meleeDefend(modifier=15, possibleDamage=a1.hit_points,
                   damageType='Bludgeoning')

    assert(a1.alive is True)
    assert(a1.stabilized is False)
    a1.Heal(10)
    assert(a1.cur_hit_points == 10)
    assert(a1.alive is True)
    assert(a1.stabilized is True)
    a1.meleeDefend(modifier=15, possibleDamage=(2 * a1.hit_points),
                   damageType='Bludgeoning')
    assert(a1.alive is False)
    assert(a1.stabilized is False)

def test_Character_Checks():
    db = InvokePSQL()
    a1 = Foe(db, foeCandidate='Skeleton', debugInd=1)
    assert(a1)
    assert(a1.getName() == "Skeleton")
    res = a1.Check('Strength', 'Normal', 5)
    assert(res is True or res is False)
    res = a1.Check('Strength', 'Advantage', 15)
    assert(res is True or res is False)
    res = a1.Check('Strength', 'Disadvantage', 10)
    assert(res is True or res is False)

    assert(res is True or res is False)
    res = a1.Check('Dexterity', 'Normal', 5)
    assert(res is True or res is False)
    res = a1.Check('Dexterity', 'Advantage', 15)
    assert(res is True or res is False)
    res = a1.Check('Dexterity', 'Disadvantage', 10)
    assert(res is True or res is False)

    assert(res is True or res is False)
    res = a1.Check('Constitution', 'Normal', 5)
    assert(res is True or res is False)
    res = a1.Check('Constitution', 'Advantage', 15)
    assert(res is True or res is False)
    res = a1.Check('Constitution', 'Disadvantage', 10)
    assert(res is True or res is False)

    assert(res is True or res is False)
    res = a1.Check('Intelligence', 'Normal', 5)
    assert(res is True or res is False)
    res = a1.Check('Intelligence', 'Advantage', 15)
    assert(res is True or res is False)
    res = a1.Check('Intelligence', 'Disadvantage', 10)
    assert(res is True or res is False)

    assert(res is True or res is False)
    res = a1.Check('Wisdom', 'Normal', 5)
    assert(res is True or res is False)
    res = a1.Check('Wisdom', 'Advantage', 15)
    assert(res is True or res is False)
    res = a1.Check('Wisdom', 'Disadvantage', 10)
    assert(res is True or res is False)

    assert(res is True or res is False)
    res = a1.Check('Charisma', 'Normal', 5)
    assert(res is True or res is False)
    res = a1.Check('Charisma', 'Advantage', 15)
    assert(res is True or res is False)
    res = a1.Check('Charisma', 'Disadvantage', 10)
    assert(res is True or res is False)

    assert(res is True or res is False)
    res = a1.Check('Athletics', 'Normal', 5)
    assert(res is True or res is False)
    res = a1.Check('Athletics', 'Advantage', 15)
    assert(res is True or res is False)
    res = a1.Check('Athletics', 'Disadvantage', 10)
    assert(res is True or res is False)
