version: '3'

services:
  pgs:
    build: ./pgs
    image: mdbdba/postgres:11
    container_name: pgs
    ports:
      - "5433:5432"
    networks:
      - rpg
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=d&d5thedition
     - POSTGRES_DB=rpg
    volumes:
     - ~/rpg/docker_data/pgs/data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  sim_graphql:
    build: ./sim_graphql
    container_name: sim_graphql
    volumes:
      - ./sim_graphql:/usr/src/app
    ports:
      - 7080:80
    networks:
      - rpg
    depends_on:
      - pgs

#  elk:
#    image: sebp/elk
#    container_name: elk
#    ports:
#      - "5601:5601"
#      - "9200:9200"
#      - "5044:5044"
#    networks:
#      - rpg
#    volumes:
#     - ~/rpg/docker_data/elk/data:/var/lib/elasticsearch
#   web:
#     image: php:apache  # pulling image from DockerHub
#     container_name: web
#     volumes:
#       - ./web:/var/www/html
#     ports:
#       - 8081:80  # host:container
#     depends_on:
#       - simrest  # website is not going to work 
#                  # unless observatory-service is running
  
networks:
  rpg:
    driver: bridge
