version: '3'

services:
  pgs:
    restart: always
    build: ./pgs
    image: mdbdba/postgres:11
    container_name: pgs
    ports:
      - "5433:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=d&d5thedition
     - POSTGRES_DB=rpg
    volumes:
     - ~/rpg/docker_data/pgs/data:/var/lib/postgresql/data

  simrest:
    build: ./simrest
    container_name: simrest
    volumes:
      - ./simrest:/usr/src/app 
    ports:
      - 6080:80
    depends_on:
      - pgs

#   web:
#     image: php:apache  # pulling image from DockerHub
#     container_name: web
#     volumes:
#       - ./web:/var/www/html
#     ports:
#       - 8081:80  # host:container
#     depends_on:
#       - simrest  # website is not going to work 
#                  # unless observatory-service is running