CREATE OR REPLACE FUNCTION reset_parties_and_characters()
RETURNS VOID AS $$
BEGIN
    TRUNCATE TABLE dnd_5e.party RESTART IDENTITY CASCADE;
    TRUNCATE TABLE dnd_5e.character RESTART IDENTITY CASCADE;
RETURN;
END;
$$ LANGUAGE plpgsql;